#database.yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.secrets[:db_username] %>
  password: <%= Rails.application.secrets[:db_password] %>
  host: localhost

development:
  <<: *default
  database: edit_development

test:
  <<: *default
  database: edit_test


production:
  <<: *default
  database: edit_production
  username: edit
  password: <%= ENV["EDIT_DATABASE_PASSWORD"] %>
